/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docs: [
    'introduction',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/upgrade',
        'getting-started/command-line',
        'getting-started/configfile',
        'getting-started/env',
      ],
    },
    {
      type: 'category',
      label: 'User Guides',
      collapsed: true,
      items: [
        'guides/questions',
        'guides/tags',
        'guides/users',
        'guides/review',
        {
          type: 'category',
          label: 'Moderation',
          collapsed: true,
          items: [
            'guides/settings',
          ],
        },
        {
          type: 'category',
          label: 'Commons',
          collapsed: true,
          items: [
            'guides/flags',
            'guides/permission',
            'guides/reputation',
          ],
        },
        'guides/plugins',
      ],
    },
    {
      type: 'category',
      label: 'Developer Guides',
      collapsed: true,
      items: [
        'development/database',
        'development/api',
      ],
    },
    'notice',
    'faq',
  ],
};
