/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docs: [
    'README',
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/upgrade',
        'getting-started/command-line',
        'getting-started/configfile',
        'getting-started/database',
        'getting-started/env',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'generated-index',
      },
      collapsed: true,
      items: [
        'guides/flags',
        // 'guides/moderation',
        'guides/permission',
        'guides/reputation',
        // 'guides/settings',
      ],
    },
    {
      type: 'category',
      label: 'Development',
      link: {
        type: 'generated-index',
      },
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Plugins',
          link: {
            type: 'doc',
            id: 'development/extending/README',
          },
          collapsed: false,
          items: [
            'development/extending/plugin-config',
            'development/extending/plugin-translation',
            'development/extending/plugin-for-ui',
          ],
        },
        {
          type: 'category',
          label: 'Contributing',
          link: {
            type: 'doc',
            id: 'development/contributing/README',
          },
          collapsed: false,
          items: [
            'development/contributing/backend',
            'development/contributing/frontend',
            'development/contributing/notice',
          ],
        },
      ],
    },
    'faq',
    {
      type: 'link',
      label: 'Support',
      href: 'https://meta.answer.dev',
    },
  ],

  // tutorialSidebar: [
    // {
    //   type: 'link',
    //   label: 'Getting Started',
    //   href: '#',
    //   className: 'section-title',
    // },
    // 'README',
    // { type: 'autogenerated', dirName: 'getting-started' },
    // {
    //   type: 'link',
    //   label: 'Recipes',
    //   href: '#',
    //   className: 'section-title',
    // },
    // { type: 'autogenerated', dirName: 'recipes' },
    // {
    //   type: 'link',
    //   label: 'Development',
    //   href: '#',
    //   className: 'section-title',
    // },
    // { type: 'autogenerated', dirName: 'development' },
    // {
    //   type: 'link',
    //   label: 'Resources',
    //   href: '#',
    //   className: 'section-title',
    // },
    // 'faq',
    // {
    //   type: 'link',
    //   label: 'Support',
    //   href: 'https://github.com/apache/incubator-answer/issues',
    // },
    // {
    //   type: 'link',
    //   label: 'Roadmap',
    //   href: 'https://github.com/orgs/apache/projects/301',
    // },

  // ],
};
